### ISSUE TITLE
How to compile the ARM ISA

### ISSUE THREAD

**Issue by cupyty** [jackwadden/VASim#35]
Nice to meet you. I'm going to use the VASim in arm architecture. but I only make the VASim for X86 ISA. How can I do for VAsim in ARM ISA?

**Comment by jackwadden** [comment]
I don't see why this wouldn't be possible. I don't think VASim (or any dependencies) has any x86 specific code. I don't have access to an ARM system, so I can't verify this though.

Currently VASim is a little difficult to build even on x86 Linux because MRNL/valijson has some preprocessor macros that are only available in C++17. This is why we require g++-5. By deleting those macros you can compile with gcc-4.6+ I believe. For your project, I expect you'll have to change some stuff around in the Makefiles of VASim and the dependencies, but with a little hacking it should work. 

Have you tried yet? Are there any errors you're getting I can take a look at. 

Let me know how it goes!

**Comment by cupyty** [comment]
Thanks to your response. I'll use the VASim as a benchmark of the gem5 simulation tool. but the gem5 simulation's configuration consists of ARM architecture. so I have one questions about using cross compiler such as arm-linux-gnueabi-g++. How about think? 
-----Original Message-----

**Comment by ted-xie** [comment]
@cupyty 
I have successfully compiled VASim for Arm before on a Raspberry pi using GCC. It should work 100%.

**Comment by jackwadden** [comment]
Sweet. Thanks for the info @ted-xie!

Closing.
