### ISSUE TITLE
gcc5 environment settings

### ISSUE THREAD

**Issue by ted-xie** [jackwadden/VASim#37]
There's some information missing from the README. If your gcc version is less than 5, then "make" will fail when building the MNRL library. To resolve, there are two methods:

1) Modify vasim/Makefile and vasim/libs/MNRL/C++/Makefile to use "g++-5" for CC rather than g++.
2) Alias g++ to g++-5.

**Comment by jackwadden** [comment]
Good point. I don't think explicitly setting g++ to g++-5 in the Makefiles is a bad idea. It's common enough now given CentOS 7 isn't in the dark ages. MNRL's valijson is a funky dependency that actually needs C++17 features that are supported in common versions of gcc 5. Otherwise, I think we could build with gcc 4.

I made two changes: 1) forced g++-5 in the top level Makefile, 2) forced the libraries (MNRL/PugiXML) to use the same compiler via the top-level Makefile.

Now building should work out of the box on both Linux and Mac as long as you have nasm and g++-5 installed.

Thanks for the issue Ted!
